### ISSUE TITLE
[Config Suggestion] Giving Mine and Slash exp instead of Minecraft exp.

### ISSUE THREAD

**Issue by AzureDoom** [kreezxil/Bane-of-Dragons#11]
It honestly makes sense to give the Mine and Slash exp. You can do this easy by having the reward do the command `/givexp @p expamount`

If you want give gear or something there are commands for that as well. [Here they are](https://github.com/RobertSkalko/Mine-and-Slash/tree/master/src/main/java/com/robertx22/commands)

**Comment by kreezxil** [comment]
and which config should I modify? I don't see these options in your mmorpg.cfg

**Comment by AzureDoom** [comment]
You want to edit the Quests in the FTB Quests. You have them giving minecraft exp, you can update that to give Mine and Slash exp via the command I listed above. You can have the quest run it as OP so it will always give the exp without needing to actually OP anyone.

**Comment by kreezxil** [comment]
ok, that makes more sense
