### ISSUE TITLE
Tech Reborn Iron Alloy Furnace cannot be opened with a right-click

### ISSUE THREAD

**Issue by WolfBV** [kreezxil/Bane-of-Dragons#13]
**Describe the bug**
When attempting to right-click an Iron Alloy Furnace from the mod Tech Reborn, the furnace's gui does not appear, similar to trying to right click a fence post or dirt block.

**To Reproduce**
1. Create a singleplayer world
2. Use creative mode to give yourself an Iron Alloy Furnace from Tech Reborn
3. Place the furnace on the ground
4. Attempt to open it with a right-click

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2844, 14.23.5.2847, 14.23.5.2847
 - Mod Pack : Bane of Dragons 1.6.7, Bane of Dragons 1.7.8, Bane of Dragons 1.8.9
 - Mod Name: Tech Reborn
 - Mod Version: 2.24.1.1017, 2.24.1.1032, 2.24.1.1032

**Additional context**
Tested using Bane of Dragons versions 1.6.7, 1.7.8, and 1.8.9. This bug appears in 1.7.8 and 1.8.9, but not in 1.6.7. This bug occurs in both singleplayer and multiplayer worlds.

**Comment by WolfBV** [comment]
Tested using Tech Reborn version 2.24.1.1032 on its own and it still happens, looks like its a problem with the mod alone.

**Comment by kreezxil** [comment]
excellent modmuss50 has tagged the report on his end meaning that he has acknowledged the bug.

**Comment by kreezxil** [comment]
And the sad part is that mod is no longer updating for 1.12.2 and further they moved to Fabric. Anyway. If you don't mind, try with lower versions until it works and if you find one that works, let me know, and I'll change it. I'm working on the successor to World of Dragons right now, World of Dragons II, and it runs in 1.16.5. Join my Discord if you want to take part in the daily alpha testing, soon to be beta testing.
