### ISSUE TITLE
[please fix] 90 degree quest not recognizing oak cabinets and ironwood cabinets

### ISSUE THREAD

**Issue by WolfBV** [kreezxil/Bane-of-Dragons#2]
After crafting 2 cabinets out of ironwood planks, the 90 degrees quest didn't complete. I thought that maybe ironwood planks just weren't the right kind for the cabinets, made 2 oak wood cabinets as well. The quest still didn't complete.

1. Craft a cabinet out of either oak wood planks or ironwood planks
2. Check on quest in the quest book

![Screen Shot 2019-09-01 at 10 57 56 PM](https://user-images.githubusercontent.com/47493126/64093182-3f7d7900-cd0c-11e9-931f-68dc133c46e8.png)
![Screen Shot 2019-09-01 at 10 57 58 PM](https://user-images.githubusercontent.com/47493126/64093183-3f7d7900-cd0c-11e9-8738-b5dc4b1ca618.png)
![Screen Shot 2019-09-01 at 10 58 05 PM](https://user-images.githubusercontent.com/47493126/64093184-40160f80-cd0c-11e9-8130-f6b98a690276.png)

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2844
 - Mod Pack : 1.3.4

This was in the bane of dragons multiplayer server.

**Comment by kreezxil** [comment]
thanks for the input

**Comment by kreezxil** [comment]
fixed via removal, there was another quest that is like but not bugged on the same panel
