### ISSUE TITLE
[please fix] arrows shoot through blocks

### ISSUE THREAD

**Issue by Drakyl** [kreezxil/Bane-of-Dragons#5]
**Describe the bug**
For reasons I cannot explain arrows can apparently shoot through blocks. WolfBV discovered this and apparently was not using anything special to accomplish it.

**To Reproduce**
1. get bow and arrow
2. shoot at target from opposite side of a block

**Versions:**

 - Minecraft: 1.12.2
 - Forge: 14.23.5.2844
 - Mod Pack : Bane of Dragons 1.5.6
 - Mod Name: 
 - Mod Version:

**Comment by kreezxil** [comment]
a regular bow and arrow? could be an issue with Mine & Slash, let AzureZhen
know about this too

**Comment by Drakyl** [comment]
Ok did some testing in single player to reproduce.  this only happens when using a Mine and Slash bow.  not only does the bow appear to shoot 3 arrows at a time it also shoots through blocks.

**Comment by Drakyl** [comment]
reported on mods github also

**Comment by Drakyl** [comment]
got response that 1.12.2 is no longer supported so I'm guessing this won't be fixed

**Comment by kreezxil** [comment]
If this is for Mine and Slash, then ping AzureDoom (previously AzureZhen)
as he's been making PR's of the project of which the author has been
willfully merging and releasing.

**Comment by AzureDoom** [comment]
This was fixed in 1.7 0
